#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CotecCelebrities.Droid.Resource", IsApplication=true)]

namespace CotecCelebrities.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int btnHector1 = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int btnHector2 = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int btnHector3 = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int btnJose1 = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int btnJose2 = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int btnJose3 = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int cade_meu_fi = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int chupa_manga = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int jaja = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int risada = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int taca_o_pal = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int uiuiuiui = 2130968581;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int hector1 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int hector2 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int hector3 = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int jose1 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int jose2 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int jose3 = 2131034116;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
